<?php
/**
 * Asset settings generated by webpack.
 *
 * WARNING: Do not edit this file!
 * It will be created and updated automatically whenever new assets are created.
 */

define( 'WP_THEME_FRONTEND_JS', 'frontend-31d6cfe0.js' );
define( 'WP_THEME_FRONTEND_CSS', 'frontend-846c6cac.css' );
define( 'WP_THEME_FRONTEND_DEPENDENCIES', [] );

define( 'WP_THEME_VERSION', '0.1.0' );
